apiVersion: security.kubearmor.com/v1
kind: DiscoveredPolicy
metadata:
  name: test-dsp
  namespace: default
spec:
  status: Inactive
  policy:
    apiVersion: security.kubearmor.com/v1
    kind: KubeArmorPolicy
    metadata:
      name: test-dsp-ksp-group-1-proc-path-block
      namespace: multiubuntu
    spec:
      severity: 5
      message: "block /bin/sleep"
      selector:
        matchLabels:
          group: group-1
      process:
        matchPaths:
        - path: /bin/sleep
      action:
        Block 