apiVersion: security.kubearmor.com/v1
kind: DiscoveredPolicy
metadata:
  name: dsp-test-ksp
spec:
  status: Inactive
  policy:
    apiVersion: security.kubearmor.com/v1
    kind: KubeArmorPolicy
    metadata:
      name: dsp-test-ksp
      namespace: default
    spec:
      severity: 5
      message: "block /bin/sleep"
      selector:
        matchLabels:
          group: group-1
      process:
        matchPaths:
        - path: /bin/sleep
      action:
        Block