name: ci-release-dsp-controller

on:
  push:
    branches:
      - "dev"
      - "discovered-policy-crd-copy"
    paths:
      - "pkg/discoveredpolicy/**"
  workflow_dispatch:

jobs:
  dsp-controller-release:
    name: Build & Push Controller
    defaults:
      run:
        working-directory: ./pkg/discoveredpolicy
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Build & Push policy controller
        run: PLATFORM=$PLATFORM make docker-buildx TAG=test-latest